import { readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT_DIR = process.cwd();
const OUTPUT_FILE = path.join(ROOT_DIR, "src", "content", "galleryManifest.ts");
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif"]);

async function existsDirectory(directoryPath) {
  try {
    const directoryStat = await stat(directoryPath);
    return directoryStat.isDirectory();
  } catch {
    return false;
  }
}

async function resolveScanDirectory() {
  const primaryNestedDir = path.join(ROOT_DIR, "gallery", "gallery1");
  if (await existsDirectory(primaryNestedDir)) {
    return {
      scanDir: primaryNestedDir,
      webPrefix: "/gallery/gallery1",
    };
  }

  const secondaryNestedDir = path.join(ROOT_DIR, "gallery", "gallery");
  if (await existsDirectory(secondaryNestedDir)) {
    return {
      scanDir: secondaryNestedDir,
      webPrefix: "/gallery/gallery",
    };
  }

  return {
    scanDir: path.join(ROOT_DIR, "gallery"),
    webPrefix: "/gallery",
  };
}

async function walkDirectory(directoryPath) {
  const entries = await readdir(directoryPath);
  const foundFiles = [];

  for (const entryName of entries) {
    const absoluteEntryPath = path.join(directoryPath, entryName);
    const entryStat = await stat(absoluteEntryPath);

    if (entryStat.isDirectory()) {
      const nestedFiles = await walkDirectory(absoluteEntryPath);
      foundFiles.push(...nestedFiles);
      continue;
    }

    const extension = path.extname(entryName).toLowerCase();
    if (IMAGE_EXTENSIONS.has(extension)) {
      foundFiles.push(absoluteEntryPath);
    }
  }

  return foundFiles;
}

function toGalleryUrl(absolutePath, scanDir, webPrefix) {
  const relativePath = path.relative(scanDir, absolutePath).split(path.sep).join("/");
  const encodedSegments = relativePath.split("/").map((segment) => encodeURIComponent(segment));
  return `${webPrefix}/${encodedSegments.join("/")}`;
}

async function generateGalleryManifest() {
  const { scanDir, webPrefix } = await resolveScanDirectory();
  const imageFiles = await walkDirectory(scanDir);
  const sortedImageFiles = imageFiles.sort((first, second) => {
    const firstRelativePath = path.relative(scanDir, first).split(path.sep).join("/");
    const secondRelativePath = path.relative(scanDir, second).split(path.sep).join("/");
    return firstRelativePath.localeCompare(secondRelativePath);
  });

  const imageUrls = sortedImageFiles.map((filePath) => toGalleryUrl(filePath, scanDir, webPrefix));

  const fileContent = `/* This file is auto-generated by scripts/genGalleryManifest.mjs */\n\nexport const galleryManifest: string[] = ${JSON.stringify(imageUrls, null, 2)};\n`;

  await writeFile(OUTPUT_FILE, fileContent, "utf8");
  console.log(`Generated gallery manifest with ${imageUrls.length} image(s).`);
}

generateGalleryManifest().catch((error) => {
  console.error("Failed to generate gallery manifest:", error);
  process.exitCode = 1;
});